;;; d2-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from d2-mode.el

(autoload 'd2-mode "d2-mode" "\


(fn)" t)
(register-definition-prefixes "d2-mode" '("d2-" "org-babel-"))

;;; End of scraped data

(provide 'd2-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; d2-mode-autoloads.el ends here
