;;; pyim-basedict-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from pyim-basedict.el

(autoload 'pyim-basedict-enable "pyim-basedict" "\
Add pyim-basedict.pyim file to `pyim-extra-dicts'." t)


;;; Generated autoloads from pyim-basedict-utils.el

(register-definition-prefixes "pyim-basedict-utils" '("pyim-basedict-"))

;;; End of scraped data

(provide 'pyim-basedict-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pyim-basedict-autoloads.el ends here
