;;; consult-eglot-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from consult-eglot.el

(autoload 'consult-eglot-symbols "consult-eglot" "\
Interactively select a symbol from the current workspace." t)
(register-definition-prefixes "consult-eglot" '("consult-eglot-"))

;;; End of scraped data

(provide 'consult-eglot-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-eglot-autoloads.el ends here
