;;; bing-dict-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from bing-dict.el

(autoload 'bing-dict-brief "bing-dict" "\
Show the explanation of WORD from Bing in the echo area.

(fn WORD &optional SYNC-P)" t)
(register-definition-prefixes "bing-dict" '("bing-dict-"))


;;; Generated autoloads from bing-dict-cache.el

(register-definition-prefixes "bing-dict-cache" '("bing-dict-"))

;;; End of scraped data

(provide 'bing-dict-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bing-dict-autoloads.el ends here
