;;; shrface-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from shrface.el

(autoload 'shrface-shr-fontize-dom "shrface" "\
Fontize the sub Optional argument DOM PROPS and FACE.

(fn DOM PROPS FACE)")
(autoload 'shrface-shr-add-props "shrface" "\
Fontize the string.
Argument START start point.
Argument END end point.
Argument PROPS text properties.

(fn START END PROPS)")
(autoload 'shrface-shr-add-face "shrface" "\
Fontize the string.
Argument START start point.
Argument END end point.
Argument FACE face.

(fn START END FACE)")
(autoload 'shrface-shr-urlify "shrface" "\
Fontize the URL.
Argument START start point.
Argument END the url.

(fn START URL &optional TITLE)")
(autoload 'shrface-bullets-level-string "shrface" "\
Return the bullets in cycle way.
Argument LEVEL the headline level.

(fn LEVEL)")
(autoload 'shrface-imenu-get-tree "shrface" "\
Produce the index for Imenu.")
(autoload 'shrface-occur "shrface" "\
Use `occur' to find all `shrface-tag-h1' to `shrface-tag-h6'.
`shrface-occur' will disable if variable `shrface-toggle-bullets' is Non-nil." t)
(autoload 'shrface-mode "shrface" "\
Toggle shr minor mode.

1. imenu
2. outline-minor-mode
3. org-indent-mode

This is a minor mode.  If called interactively, toggle the
`Shrface mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `shrface-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "shrface" '("shrface-"))

;;; End of scraped data

(provide 'shrface-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shrface-autoloads.el ends here
