;;; language-detection-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from language-detection.el

(autoload 'language-detection-buffer "language-detection" "\
Predict the programming language of the current buffer and output it to messages.

(fn &optional PRINT-MESSAGE)" t)
(autoload 'language-detection-string "language-detection" "\
Return the predicted programming language of STRING as a symbol.

(fn STRING)")
(register-definition-prefixes "language-detection" '("language-detection-"))

;;; End of scraped data

(provide 'language-detection-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; language-detection-autoloads.el ends here
