;;; osx-dictionary-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from osx-dictionary.el

(autoload 'osx-dictionary-search-input "osx-dictionary" "\
Search input word and display result with buffer." t)
(autoload 'osx-dictionary-search-pointer "osx-dictionary" "\
Search word around and display result with buffer." t)
(defalias 'osx-dictionary-search-word-at-point 'osx-dictionary-search-pointer)
(autoload 'osx-dictionary-get-all-dictionaries "osx-dictionary" "\
Get all dictionaries as a list.")
(register-definition-prefixes "osx-dictionary" '("osx-dictionary-"))

;;; End of scraped data

(provide 'osx-dictionary-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; osx-dictionary-autoloads.el ends here
