;;; aria2-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from aria2.el

(autoload 'aria2-downloads-list "aria2" "\
Display aria2 downloads list.  Enable `aria2-mode' to controll the process." t)
(register-definition-prefixes "aria2" '("aria2-"))

;;; End of scraped data

(provide 'aria2-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; aria2-autoloads.el ends here
