SPC: Spacebar
SPC  -> SPC A
SPC  -> SPC B
SPC  -> SPC C
SPC  -> SPC D
SPC  -> SPC E
SPC  -> SPC F
SPC  -> SPC G
SPC  -> SPC H
SPC  -> SPC I
SPC  -> SPC J
SPC  -> SPC K
SPC  -> SPC L
SPC  -> SPC M
SPC  -> SPC N
SPC  -> SPC O
SPC  -> SPC P
SPC  -> SPC Q
SPC  -> SPC R
SPC  -> SPC S
SPC  -> SPC T
SPC  -> SPC U
SPC  -> SPC V
SPC  -> SPC W
SPC  -> SPC X
SPC  -> SPC Y
SPC  -> SPC Z

