;;; color-theme-sanityinc-solarized-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from color-theme-sanityinc-solarized.el

(when (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(autoload 'color-theme-sanityinc-solarized-dark "color-theme-sanityinc-solarized" "\
Apply the dark solarized theme." t)
(autoload 'color-theme-sanityinc-solarized-light "color-theme-sanityinc-solarized" "\
Apply the light solarized theme." t)
(register-definition-prefixes "color-theme-sanityinc-solarized" '("color-theme-sanityinc-solarized"))

;;; End of scraped data

(provide 'color-theme-sanityinc-solarized-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; color-theme-sanityinc-solarized-autoloads.el ends here
