;;; el-fetch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from el-fetch.el

(autoload 'el-fetch "el-fetch" "\
Show system information in Neofetch-like style (eg CPU, RAM)." t)
(register-definition-prefixes "el-fetch" '("el-fetch-"))

;;; End of scraped data

(provide 'el-fetch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; el-fetch-autoloads.el ends here
