;;; khoj-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from khoj.el

(autoload 'khoj "khoj" "\
Provide natural, search assistance for your notes, transactions and images." t)
(register-definition-prefixes "khoj" '("khoj-"))

;;; End of scraped data

(provide 'khoj-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; khoj-autoloads.el ends here
