;;; repeat-help-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from repeat-help.el

(defvar repeat-help-mode nil "\
Non-nil if Repeat-Help mode is enabled.
See the `repeat-help-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `repeat-help-mode'.")
(custom-autoload 'repeat-help-mode "repeat-help" nil)
(autoload 'repeat-help-mode "repeat-help" "\
Enable a prompt with key descriptions for `repeat-mode'.

   
Repeat Help Mode enables a prompt with available keys and actions
when repeating commands using `repeat-mode'.

The prompt can be displayed using Embark (default) or a Which Key
menu. If neither package is available, it falls back on the echo
area message built into `repeat-mode'.

This is a global minor mode.  If called interactively, toggle the
`Repeat-Help mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='repeat-help-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "repeat-help" '("repeat-help-"))

;;; End of scraped data

(provide 'repeat-help-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; repeat-help-autoloads.el ends here
